version: '3'

services:
  db:
    image: percona:8.0.28-19
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    networks:
      - app_network

  lb:
    image: nginx:1.22.0
    restart: always
    networks:
      - app_network
    ports:
      - 8080:80
    volumes:
      - './lb/nginx.conf:/etc/nginx/nginx.conf'

  app1:
    image: nginx:1.22.0
    restart: always
    networks:
      - app_network
    volumes:
       - './app1:/usr/share/nginx/html'


  app2:
    image: nginx:1.22.0
    restart: always
    networks:
      - app_network
    volumes:
       - './app2:/usr/share/nginx/html'

networks:
  app_network:


